# This is a workflow to update the emails, schedule, and syllabus pages 
# each time a change is made to any of the prompts or to the wording of
# the email text.

name: Generate_materials

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: ['Prompts/**', 'Weekly_Emails/Email_Text/**', 'scripts/**']
    
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run all scripts
        run: |
          bash scripts/run_all.sh
          
      - name: Commit newly updated files
        run:
          git config --local user.name actions-user

          git config --local user.email "actions@github.com" 
 
          git fetch

          git add *

          git commit -am "GH Action Files autotmatically updated" 
 
          git push -f origin main
